### ISSUE TITLE
override files not workin

### ISSUE THREAD

**Issue by stoeffel** [heinzelmannchen/BA#65]
Es gibt immer noch ein problem beim überschreiben von files.
Beim Ausführen von `node create.js`gibt es folgenden Fehler, auch bei gesetztem Flag.

```
Trace
    at /Users/stoeffel/src/BA/heinzelmannchen/integrationTests/create.js:11:13
    at _rejected (/Users/stoeffel/src/BA/heinzelmannchen/node_modules/q/q.js:797:24)
    at /Users/stoeffel/src/BA/heinzelmannchen/node_modules/q/q.js:823:30
    at Promise.when (/Users/stoeffel/src/BA/heinzelmannchen/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/Users/stoeffel/src/BA/heinzelmannchen/node_modules/q/q.js:741:41)
    at /Users/stoeffel/src/BA/heinzelmannchen/node_modules/q/q.js:557:44
    at flush (/Users/stoeffel/src/BA/heinzelmannchen/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)
{ '0': [Error: file ./foo/bar/occupation.md already exists, use override flag] }
```

**Comment by sprengr** [comment]
sollte nach npm install funktionieren
